//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class acaxp
    {
        public int acaxpCaxp { get; set; }
        public int acaxpCprf { get; set; }
        public int acaxpCmod { get; set; }
        public int acaxpCapp { get; set; }
        public int acaxpeGra { get; set; }
        public int acaxpeEli { get; set; }
        public int acaxpeAct { get; set; }
        public int acaxpeBus { get; set; }
        public int acaxpStat { get; set; }
        public int acaxpRide { get; set; }
    
        public virtual acapp acapp { get; set; }
        public virtual acprf acprf { get; set; }
        public virtual acmod acmod { get; set; }
    }
}
