//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class acepc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public acepc()
        {
            this.acmxe = new HashSet<acmxe>();
            this.acpxe = new HashSet<acpxe>();
            this.acuxe = new HashSet<acuxe>();
            this.acuxp = new HashSet<acuxp>();
            this.flotas = new HashSet<flotas>();
            this.viaje = new HashSet<viaje>();
        }
    
        public int acepcCepc { get; set; }
        public string acepcNomb { get; set; }
        public string acepcSigl { get; set; }
        public int acepcNrou { get; set; }
        public int acepcRubr { get; set; }
        public string acepcMisn { get; set; }
        public string acepcDbnm { get; set; }
        public string acepcScnx { get; set; }
        public System.DateTime acepcFreg { get; set; }
        public System.DateTime acepcFvto { get; set; }
        public int acepcStat { get; set; }
        public int acepcRide { get; set; }
    
        public virtual accon accon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acmxe> acmxe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acpxe> acpxe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acuxe> acuxe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acuxp> acuxp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flotas> flotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<viaje> viaje { get; set; }
    }
}
