//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class aclgn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aclgn()
        {
            this.aclog = new HashSet<aclog>();
        }
    
        public int aclgnClgn { get; set; }
        public string aclgnCusr { get; set; }
        public string aclgnSess { get; set; }
        public string aclgnHNam { get; set; }
        public string aclgnISrv { get; set; }
        public System.DateTime aclgnFsys { get; set; }
    
        public virtual acusr acusr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aclog> aclog { get; set; }
    }
}
