//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class acmxe
    {
        public int acmxeCmxe { get; set; }
        public int acmxeCepc { get; set; }
        public int acmxeCmod { get; set; }
        public int acmxeStat { get; set; }
        public int acmxeRide { get; set; }
    
        public virtual acepc acepc { get; set; }
        public virtual acmod acmod { get; set; }
    }
}
