//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class acpme
    {
        public int acpmeCpme { get; set; }
        public int acpmeCfll { get; set; }
        public int acpmeCdwr { get; set; }
        public int acpmeCdvi { get; set; }
        public string acpmePass { get; set; }
        public int acpmeStat { get; set; }
    }
}
