//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuxe
    {
        public int acuxeCuxe { get; set; }
        public string acuxeCusr { get; set; }
        public int acuxeCepc { get; set; }
        public int acuxeStaU { get; set; }
        public System.DateTime acuxeFtra { get; set; }
        public System.DateTime acuxeFvto { get; set; }
        public int acuxeStat { get; set; }
        public int acuxeRide { get; set; }
    
        public virtual acepc acepc { get; set; }
        public virtual acusr acusr { get; set; }
    }
}
