//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class acuxp
    {
        public int acuxpCuxp { get; set; }
        public string acuxpCusr { get; set; }
        public int acuxpCprf { get; set; }
        public int acuxpCepc { get; set; }
        public int acuxpStat { get; set; }
        public int acuxpRide { get; set; }
    
        public virtual acepc acepc { get; set; }
        public virtual acprf acprf { get; set; }
        public virtual acusr acusr { get; set; }
    }
}
