//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcEntities : DbContext
    {
        public AcEntities()
            : base("name=AcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acapp> acapp { get; set; }
        public virtual DbSet<acaxp> acaxp { get; set; }
        public virtual DbSet<accon> accon { get; set; }
        public virtual DbSet<acepc> acepc { get; set; }
        public virtual DbSet<aclgn> aclgn { get; set; }
        public virtual DbSet<aclog> aclog { get; set; }
        public virtual DbSet<acmod> acmod { get; set; }
        public virtual DbSet<acmxe> acmxe { get; set; }
        public virtual DbSet<acpme> acpme { get; set; }
        public virtual DbSet<acprf> acprf { get; set; }
        public virtual DbSet<acpxe> acpxe { get; set; }
        public virtual DbSet<acser> acser { get; set; }
        public virtual DbSet<acusr> acusr { get; set; }
        public virtual DbSet<acuxe> acuxe { get; set; }
        public virtual DbSet<acuxp> acuxp { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
