//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadoasientos
    {
        public int Id { get; set; }
        public Nullable<int> DisenoFlotaId { get; set; }
        public string CodAsiento { get; set; }
        public int Estado { get; set; }
    
        public virtual disenoflota disenoflota { get; set; }
    }
}
