//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class flotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flotas()
        {
            this.disenoflota = new HashSet<disenoflota>();
            this.viajeflota = new HashSet<viajeflota>();
        }
    
        public int Id { get; set; }
        public int TipoIdc { get; set; }
        public int EmpresaId { get; set; }
        public string Placa { get; set; }
        public string Chofer { get; set; }
        public string Ayudante { get; set; }
        public int NroPisos { get; set; }
    
        public virtual acepc acepc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disenoflota> disenoflota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<viajeflota> viajeflota { get; set; }
    }
}
