//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public viaje()
        {
            this.viajecliente = new HashSet<viajecliente>();
            this.viajeflota = new HashSet<viajeflota>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<System.DateTime> Horario { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual acepc acepc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<viajecliente> viajecliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<viajeflota> viajeflota { get; set; }
    }
}
