//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viajeflota
    {
        public int Id { get; set; }
        public int ViajeId { get; set; }
        public int FlotaId { get; set; }
    
        public virtual flotas flotas { get; set; }
        public virtual viaje viaje { get; set; }
    }
}
