//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA.MODELDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viajecliente
    {
        public int id { get; set; }
        public int viajeid { get; set; }
        public int clienteid { get; set; }
        public Nullable<int> asientoId { get; set; }
        public string ci { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual viaje viaje { get; set; }
    }
}
